### ISSUE TITLE
Introduction_Purpose of the study

### ISSUE THREAD

**Issue by florencemayo** [nattaponx/master_thesis_2016#11]
A summary of the following :

The intention of the study?
For what purpose?
What does a case study includes? Discussion of stakeholders to get metrics, developing a prototype or a tool to visualize elektra.
Reference again if it has been done before ..
What is your aim.

**Comment by nattaponx** [comment]
I think this is not done yet

**Comment by nattaponx** [comment]
Reviewed/done
