### ISSUE TITLE
Introduction_Statement of Problems

### ISSUE THREAD

**Issue by florencemayo** [nattaponx/master_thesis_2016#14]
What is the main problem?
What will the research investigate?

**Comment by florencemayo** [comment]
I am still unsure of the problem. perhaps we can keep one problem and omit the second one.

**Comment by nattaponx** [comment]
You mean the consistency? I think we can keep it as our improved v isulization of key component helps indirectly. (I can explain it to you later)

**Comment by florencemayo** [comment]
we can keep it, the explanation is good.

**Comment by nattaponx** [comment]
Reviewed/done
