### ISSUE TITLE
Introduction_Background

### ISSUE THREAD

**Issue by florencemayo** [nattaponx/master_thesis_2016#19]
To be reviewed

**Comment by florencemayo** [comment]
In the FIRST paragraph of a background section, you have talked about a number of software being deployed in a car and that results to a huge number of ECUs. I was wondering if you can add a reference to make the statement solid.

**Comment by florencemayo** [comment]
The figure TEMPORARY? What do you think we can use to replace it?

**Comment by florencemayo** [comment]
Next time, we need to ask about a low level architecture and a high level architecture. I am still unsure about this. OR if you have a better understanding, then you can explain to me

**Comment by nattaponx** [comment]
Add ref to the first paragraph
I was thinking of putting an example of automotive architecture. Maby we can ask Ulf for a screenshot of one of the architecture diagrams from Volvo or just use one from his work.

**Comment by nattaponx** [comment]
Do we need to italize 'Elektra' every time in the report?

**Comment by nattaponx** [comment]
Reviewed/done

**Comment by nattaponx** [comment]
Reviewed/done
