### ISSUE TITLE
Introduction _ first_paragraph

### ISSUE THREAD

**Issue by florencemayo** [nattaponx/master_thesis_2016#22]
Chapter 1
Changed communication between LCs to connection between LCs
Changed key components top key artifacts, NOTE : artifacts covers components, ports, data elements and other staffs.
I think we need to add a reference to the section that talks about the inconsistency between the two architectures. Ulf paper
I THINK WE DO NOT NEED THIS PARAGRAPH : Furthermore, the diagram at VCG does not only contain the components, ports, and connections, but also a logical designs. This makes the document even bigger and harder for stakeholders to focus on only the parts that they have an interest in. \ 
We need to change the term “visualization tool”, we are not having a tool nor making a tool
Is it electrical architecture or electrical architectureS?
We also need to formulate question 4
Adding one more research question that will talk about how we intend to balance the low level and high level architecture.

**Comment by florencemayo** [comment]
THE FIRST PARAGRAPH IS EDITED

**Comment by nattaponx** [comment]
Reviewed/done
