### ISSUE TITLE
Acknowledgement

### ISSUE THREAD

**Issue by nattaponx** [nattaponx/master_thesis_2016#3]

**Comment by nattaponx** [comment]
Should the professors' names be their full names?

**Comment by florencemayo** [comment]
not important, Hakan needs to be added

**Comment by florencemayo** [comment]
I am not sure of the names. Done, Ready for review

**Comment by nattaponx** [comment]
- Names shouldn't be put in \texttt{}. they look like variables to me
- Be aware of using 'Elektra'

**Comment by nattaponx** [comment]
Reviewed/done
