### ISSUE TITLE
Introduction_1.0

### ISSUE THREAD

**Issue by nattaponx** [nattaponx/master_thesis_2016#4]
What has to be included ?
SECTION_1
1. What is software visualization in general?
2. Why is it important in general, we can add on what we have learned in brief, its importances?
3. A reference can be added to elaborate more.
4. Any side effects (negative effects) of doing visualization, provide references if available.
5. Has their any research done on this area, describe briefly if you have one.
6. Briefly, what will we do, what are the challenges, any research that has been done? and what is the proposed solution?

**Comment by florencemayo** [comment]
I edited first paragraph. Please go through it.

**Comment by nattaponx** [comment]
Reviewed
